import Head from 'next/head';
import Navbar from './Navbar';
import styles from "../styles/Home.module.css";

export default function Layout({ children, ...props }) {
  return (
    <div>
      <Head>
        <title>Muse Filez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/museLogo.jpg" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <h1 className={styles.title}>
          MUSE FILEZ!
        </h1>

        <p className={styles.description}>
          Access Exclusive Content!
        </p>
        {children}
      </main>
      <footer className={styles.footer}>
        <a
          href="http://mfilez.io/"
          target="_blank"
          rel="noopener noreferrer"
        >
          © 2023 Muse Filez
        </a>
      </footer>
    </div>
  );
}